"""Make active_until NOT NULL

Revision ID: 65b878b75e4b
Revises: 
Create Date: 2025-01-27 05:58:30.115286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b878b75e4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'active_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('promo_codes', 'active_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'active_until',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('promo_codes', 'active_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
